/**
 * This code was generated by Builder.io.
 */
import React from "react";

import RegistrationForm2 from "../RegistrationForm/RegistrationForm2";

import styles from "./MainComponent.module.css";

const MainComponent = () => {
  return (
    <div className={styles.mainContainer}>
      
      <main className={styles.mainContent}>
        <RegistrationForm2 />
      </main>
     
    </div>
  );
};

export default MainComponent;
