/**
 * This code was generated by Builder.io.
 */
import React from "react";

import HeroSection from "./HeroSection";
import AboutSection from "./AboutSection";
import TeamSection from "./TeamSection";
import WhyChooseUs from "./WhyChooseUs";
import Statistics from "./Statistics";

import styles from "./CourseDetails.module.css";

function CourseDetails() {
  return (
    <div className={styles.courseDetails}>
    
      <div className={styles.indicator} />
      <HeroSection />
      <AboutSection />
      <TeamSection />
      <WhyChooseUs />
      <Statistics />
      
    </div>
  );
}

export default CourseDetails;
